### ISSUE TITLE
Unexpected unparsed bytes

### ISSUE THREAD

**Issue by olanod** [Zondax/ledger-statemine#11]
Couldn't make a normal `balances.transfer` with the latest XL app installed.

**Comment by S0c5** [comment]
Please, I'm facing the same issue.

**Comment by raynaudoe** [comment]
Hi, are you using the latest release v3.504.0 ?

**Comment by olanod** [comment]
Yep, I grabbed the latest
```
$ ./installer_statemine_XL version
v3.504.0
```

**Comment by raynaudoe** [comment]
Ok, could you please paste the input parameters that you're trying to use when calling `transfer` ?
