### ISSUE TITLE
PolkadotXcm.limited_teleport_assets() support request.

### ISSUE THREAD

**Issue by stepanLav** [Zondax/ledger-statemine#36]
In the [NovaWallet](https://novawallet.io/) we have pretty easy way to send assets between different chains with `PolkadotXcm.limited_teleport_assets()`.
Example of such transaction - https://statemine.subscan.io/extrinsic/3447529-2?event=3447529-4

Our users would be very glad to use the ledger in such scenarios. Is there any possibility that this functionality could be supported?

**Comment by ainhoa-a** [comment]
Hi @stepanLav  we'll look into it.
